loop/main/routes.py
import re
from flask import render_template, url_for, flash, redirect, request, Blueprint
from loop import db
from loop.collaborative_filter import CollaborativeFilter
from loop.imdb_movies import ImdbMovies
from loop.main.forms import GroupForm, cinema_list, MovieSearchForm, SelectGenreForm, ContactForm
from loop.main.forms import LikeForm, DislikeForm, DeleteAllForm
from loop.group_history import GroupHistory
from loop.models import Movies, Preferences, GroupResults
from flask_login import current_user, login_required
# from loop.cinema import CinemaMovies
from loop.algorithm import Algorithms
from loop.movie_search import MovieSearch
from loop.movie_categories import Genres
import unidecode
from loop import mail
from flask_mail import Message

# from loop.update_movie_db import UpdateMovieDatabase

main = Blueprint('main', __name__)


@main.route("/watch", methods=['GET', 'POST'])
@login_required
def watch():
    # update_db = UpdateMovieDatabase()
    # update_db.insert_movies()
    # initialise forms
    form = MovieSearchForm()
    like_form = LikeForm()
    dislike_form = DislikeForm()
    # check if the form has been submitted
    if like_form.is_submitted() and like_form.like_movie.data:
        # Query the database to get the selected movie
        preference = Preferences.query.filter_by(movie=like_form.like_movie.data, user_id=current_user.id).first()
        # if the movie is not found in the db, then add it
        if not preference:
            liked_movie = Preferences(movie=like_form.like_movie.data, author=current_user, like=1, dislike=0)
            db.session.add(liked_movie)
            db.session.commit()
            flash('You liked ' + like_form.like_movie.data, 'success')
        # if the movie is found and has the same preference, then remove it
        elif preference.like == 1:
            delete_vote(preference.id)
        # else change the preference type
        else:
            update_vote(preference.id)

    if dislike_form.is_submitted() and dislike_form.dislike_movie.data:
        preference = Preferences.query.filter_by(movie=dislike_form.dislike_movie.data, user_id=current_user.id).first()
        if not preference:
            disliked_movie = Preferences(movie=dislike_form.dislike_movie.data, author=current_user, like=0, dislike=1)
            db.session.add(disliked_movie)
            db.session.commit()
            flash('You disliked ' + dislike_form.dislike_movie.data, 'success')
        elif preference.like == 0:
            delete_vote(preference.id)
        else:
            update_vote(preference.id)

    # get all the voted on movie for the current user
    already_voted = Preferences.query.filter_by(user_id=current_user.id)
    movie_choices = {movie.movie: (movie.like, movie.dislike) for movie in already_voted}

    # initialise the collaborative filter
    collaborative_filter = CollaborativeFilter()
    genre_form = SelectGenreForm()
    genres = Genres()
    # global selected_genre
    selected_genre = {}
    if genre_form.genre.data not in ['None', 'Select']:
        selected_genre = genres.movies_genres(genre_form.genre.data)
    return render_template('watch.html', title='Watch', form=form, genre_form=genre_form, like_form=like_form,
                           already_voted=movie_choices, dislike_form=dislike_form, selected_genre=selected_genre,
                           popular_latest_movies=genres.popular_latest_movies(),
                           collaborative_filter=collaborative_filter.get_recommendation())


@main.route("/movie_recommendation", methods=['GET', 'POST'])
@login_required
def movie_recommendation():
    # when the form is submitted, this method gets the value of the form request
    movie = request.form.get("search")
    if movie:
        # search for the movie or a bit of of the movie in the db
        search_result = Movies.query.filter(Movies.title.ilike('%' + movie + '%')).first()
        if search_result:
            # get the recommendation from movies passed in
            movies = MovieSearch(search_result)
            return render_template('movie_recommendation.html', title='Movie recommendation',
                                   movies=movies.get_recommendation())
        # if the movie passed in is not in the db
        else:
            flash('Search Unsuccessful. Please check spelling again.', 'danger')
    return redirect(url_for('main.watch'))


@main.route("/profile", methods=['GET', 'POST'])
@login_required
def profile():
    # deleting all values in a particular section
    delete_all_form = DeleteAllForm()
    if delete_all_form.is_submitted():
        # delete all liked movies
        if delete_all_form.delete_records.raw_data[1] == "like":
            likes = Preferences.query.filter_by(like=1, user_id=current_user.id)
            for like in likes:
                delete_vote(like.id)
        elif delete_all_form.delete_records.raw_data[1] == "dislike":
            # delete all disliked movies
            dislikes = Preferences.query.filter_by(dislike=1, user_id=current_user.id)
            for dislike in dislikes:
                delete_vote(dislike.id)
        else:
            # delete all group recommendations
            records = GroupResults.query.filter_by(user_id=current_user.id)
            for record in records:
                delete_group_vote(record.id)

    # get voted on movies
    likes = Preferences.query.filter_by(like=1, user_id=current_user.id)
    dislikes = Preferences.query.filter_by(dislike=1, user_id=current_user.id)
    # declare the group history data
    group_history = GroupHistory()
    history = group_history.get_history()
    # group history list of data for the graph
    ranking = group_history.get_rankings()
    return render_template('profile.html', likes=likes, dislikes=dislikes, history=history, group_values=ranking,
                           delete_all_form=delete_all_form)


@main.route("/profile/<int:vote_id>/update", methods=['GET', 'POST'])
@login_required
def update_vote(vote_id):
    # swap the values from a like to dislike or vice versa for movies already rated
    movie = Preferences.query.get_or_404(vote_id)
    if movie.like == 1:
        movie.like = 0
        movie.dislike = 1
        flash(movie.movie + ' has been added to your disliked list', 'success')
    else:
        movie.like = 1
        movie.dislike = 0
        flash(movie.movie + ' has been added to your liked list', 'success')
    db.session.commit()
    return redirect(url_for('main.profile'))


@main.route("/profile/<int:vote_id>/delete", methods=['POST'])
@login_required
def delete_vote(vote_id):
    # remove the previous voted preference for a particular movie
    movie = Preferences.query.get_or_404(vote_id)
    db.session.delete(movie)
    db.session.commit()
    if movie.like == 1:
        flash(movie.movie + ' has been removed from your liked list', 'success')
    else:
        flash(movie.movie + ' has been removed from your disliked list', 'success')
    return redirect(url_for('main.profile'))


@main.route("/profile/<int:group_id>/delete_record", methods=['POST'])
@login_required
def delete_group_vote(group_id):
    # remove the previous group history record
    group_result = GroupResults.query.get_or_404(group_id)
    db.session.delete(group_result)
    db.session.commit()
    flash(group_result.winner + ' has been removed', 'success')
    return redirect(url_for('main.profile'))


@main.route("/group_landing", methods=['GET', 'POST'])
@login_required
def group_landing():
    # render a landing page, for a user to specify the group options
    return render_template('group_landing.html', title='Group Landing')

# Reason for not using the cinema data, is because the cinemas are closed, so there is none
# @main.route("/group", methods=['GET', 'POST'])
# @login_required
# def group():
#     # get the cinema form check list with all the current movie sin the cinema
#     cinema_movies = CinemaMovies()
#     people_form = GroupForm()
#     cinema_form = cinema_list(cinema_movies.get_movies())
#     return render_template('group.html', title='Group', people_form=people_form, group_size=people_form.amount.data,
#                            cinema_form=cinema_form)


@main.route("/group", methods=['GET', 'POST'])
@login_required
def group():
    # get the cinema form check list with all the current movie sin the cinema
    imdb_movies = ImdbMovies()
    people_form = GroupForm()
    imdb_form = cinema_list(imdb_movies.get_movies())
    return render_template('group.html', title='Group', people_form=people_form, group_size=people_form.amount.data,
                           cinema_form=imdb_form)


# This is used for the access the eye cinema movie website
def format_movie_title(movie):
    # Removing unwanted characters in the movie name except for a hyphen '-'
    format_title = re.sub(r'[^\w\s-]', '', movie["movie"])
    unaccented_string = unidecode.unidecode(format_title)
    # replacing spaces with a "-"
    return unaccented_string.replace(' ', '-')

# Reason for not using the cinema data, is because the cinemas are closed, so there is none
# @main.route("/group_recommendation", methods=['GET', 'POST'])
# @login_required
# def get_group_recommendation():
#     cinema_movies = CinemaMovies()
#     cinema_details = cinema_movies.get_movie_details()
#     group_ratings_form = []
#     # Getting all the values from the group form
#     for index in range(len(request.form)):
#         try:
#             group_ratings_form.append(request.form['input_rating_' + str(index)])
#         except KeyError:
#             break
#
#     # Checking if the form was completed
#     if group_ratings_form:
#         # Get the results from the algorithms
#         algorithm = Algorithms(group_ratings_form)
#         movies = algorithm.run()
#         top_movie, other_movies = [], []
#         counter = 0
#         for movie in movies:
#             cinema_url = cinema_details[1]

loop/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from loop import db, bcrypt
from loop.users.forms import RegistrationForm, LoginForm
from loop.models import Users
from flask_login import login_user, current_user, logout_user

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    # ensure that if the user is logged in, then they cannot register another account
    if current_user.is_authenticated:
        return redirect(url_for('main.watch'))
    form = RegistrationForm()
    # when the form has been filled and submitted, encypt the password before saving it in the database
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = Users(first_name=form.first_name.data, last_name=form.last_name.data, email=form.email.data,
                     password=hashed_password)
        # adding this entry to the db
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/", methods=['GET', 'POST'])
@users.route("/login", methods=['GET', 'POST'])
def login():
    # ensure that if the user is logged in, then they cannot login to another account
    if current_user.is_authenticated:
        return redirect(url_for('main.watch'))
    form = LoginForm()
    # when the form has been filled and submitted, verify that the credentials are in the database
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            # if there was a page clicked before the login, it will be redirected to it after the login
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.watch'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


# logout function
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('users.login'))

loop/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <h1>{{ current_user.first_name }} {{ current_user.last_name }}</h1>

        <div class="col-md-4">
          <div class="content-section">
            <h3>Genres</h3>
            <p class='text-muted'>What type of movie are you looking for?</p>
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">genre 1</li>
                <li class="list-group-item list-group-item-light">genre 2</li>
                <li class="list-group-item list-group-item-light">genre 3</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
          </div>
        </div>
{% endblock content %}

loop/templates/contact.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col mb-5">
            <div class="card">
                <div class="card-header bg-primary text-white"><i class="fa fa-envelope"></i> Contact us.</div>
                <div class="card-body">
                    <form action="{{ url_for('main.contact') }}" method="POST">
                      {{ form.csrf_token }}
                      <div class="form-group">
                        {{ form.email.label }}
                        {{ form.email(class='form-control') }}
                        {% for error in form.email.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                      </div>

                      <div class="form-group">
                        {{ form.subject.label }}
                        {{ form.subject(class='form-control') }}
                        {% for error in form.subject.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                      </div>

                      <div class="form-group">
                        {{ form.message.label }}
                        {{ form.message(class='form-control') }}
                        {% for error in form.message.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                      </div>
                      {{ form.submit(class='btn btn-primary') }}
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card mb-3">
                <div class="card-header bg-success text-white"><i class="fas fa-info-circle"></i> About</div>
                <div class="card-body">
                    <p><b>Title:</b> Loop</p>
                    <p><b>Project:</b> Final Year Project</p>
                    <p><b>Name:</b> Louis Ambrose</p>
                    <p><b>Email:</b> l.ambrose1@nuigalway.ie</p>
                    <p><b>Git:</b> https://github.com/lambrose</p>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock content %}

loop/templates/group_chat_options.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-6 col-sm-9 mt-4 px-md-5 left_group_landing">
            <form id="create_room_form" method='POST' action='/group_chat'>
                    {{ create_form.hidden_tag() }}
                 <legend class="border-bottom mt-3"><b>Create a chat room</b></legend>
                    <fieldset class='form-group'>
                       {{ create_form.voters.label(class="form-control-label") }}
                       {% if create_form.voters.errors %}
                            {{ create_form.voters(class='form-control form-control-lg is-invalid') }}
                            <div class='invalid-feedback'>
                                {% for error in create_form.voters.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ create_form.voters(class='form-control form-control-lg') }}
                        {% endif %}
                    </fieldset>
                    <div class='form-group'>
                        {{ create_form.submit(class='btn btn-success') }}
                    </div>
                </form>

            <button type="button" class="btn btn-info mb-2" data-toggle="collapse" data-target="#create_i">Instructions</button>
            <div id="create_i" class="collapse">
                <ol class="mt-4">
                    <li>This feature requires one group member to specify the amount of voters in a group.</li>
                    <li>The term "voting" or "voter" refers to a user who wants to select a movie for the pool of movies to be collectively rated.</li>
                    <li>If you complete the form and you are not redirected into a room, then all rooms are occupied. Please try again in a few moments.</li>
                </ol>
            </div>
        </div>

        <div class="col-lg-6 col-sm-9 mt-4 px-md-5 right_group_landing">
            <form id="join_room_form" method='POST' action='/group_chat'>
                    {{ join_form.hidden_tag() }}
                 <legend class="border-bottom mt-3"><b>Join a chat room</b></legend>
                    <fieldset class='form-group'>
                       {{ join_form.room.label(class="form-control-label") }}
                       {% if join_form.room.errors %}
                            {{ join_form.room(class='form-control form-control-lg is-invalid') }}
                            <div class='invalid-feedback'>
                                {% for error in join_form.room.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ join_form.room(class='form-control form-control-lg') }}
                        {% endif %}
                    </fieldset>
                    <div class='form-group'>
                        {{ join_form.submit(class='btn btn-primary') }}
                    </div>
                </form>

            <button type="button" class="btn btn-info mb-2" data-toggle="collapse" data-target="#join_i">Instructions</button>
        <div id="join_i" class="collapse">
             <ol class="mt-4">
                <li>This feature requires other group members to specify the a created room number to join a chat room.</li>
                <li>If you complete the form and you are not redirected into a room, then check that you entered the correct room number or
                      check that that room has been created.</li>
             </ol>
          </div>
        </div>
    </div>
</div>
{% endblock content %}

loop/templates/group_landing.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="col-8">
        <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#group_i"><i class="fas fa-info-circle"></i></button>
        <div id="group_i" class="collapse white_text">
        <br>
        <b> How we determine a group recommendation:</b><br>
            <ol>
                <li>We have designed and implemented nine algorithms for this recommendation.<br>
                    <ul><li>Additive Utilitarian</li>
                        <li>Multiplicative Utilitarian</li>
                        <li>Borda Count</li>
                        <li>Copend Rule</li>
                        <li>Plurality Voting</li>
                        <li>Approval Voting</li>
                        <li>Least Misery</li>
                        <li>Most Pleasure</li>
                        <li>Average without Misery</li>
                    </ul></li>
                <li>All nine algorithms are executed. Then the top results are then taken from each algorithm.</li>
                <li>The movie that has occurred the most from the individual results is determined as the most suitable movie.</li>
            </ol>
      </div>
    </div>
    <div class="row">
          <div class="col-lg-6 col-sm-9 mt-4 px-md-5 left_group_landing">
              <legend class="border-bottom mt-3"><b>Choice 1</b></legend>
              <h5>All group members can complete a group recommendation on this account.</h5>
            <a class="btn btn-success" href="{{ url_for('main.group') }}">Group</a>

              <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#option_1">Instructions</button>
              <div id="option_1" class="collapse">
                  <ol class="mt-4">
                    <li>This feature requires all users participating in the group feature to complete a form on one account.</li>
                    <li>Please specify how many people are in the group, that will be voting on their preferred movie.</li>
                    <li>Then please select the movies that you would like to watch. Note, each member of the group can only select a maximum of one movie.
                       E.g. If there are 3 people in the group, then only a maximum of 3 movies can be selected. Then confirm your
                       selection by clicking "Confirm Movies".</li>
                    <li>In the table provided, each user should assign a preference score from 1 to 10 across all movies. 10 being the
                       most preferred movie and 1 being the least preferred movie. Then confirm your inputs by clicking "Confirm Inputs".</li>
                  </ol>
              </div>
          </div>
        <div class="col-lg-6 col-sm-9 mt-4 px-md-5 right_group_landing">
            <legend class="border-bottom mt-3"><b>Choice 2</b></legend>
            <h5>A group can create a chat to complete a group recommendation on their individual accounts.</h5>

            <a class="btn btn-success" href="{{ url_for('chat.group_chat_options') }}">Group chat</a>

              <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#option_2">Instructions</button>
              <div id="option_2" class="collapse">
                  <ol class="mt-4">
                      <li>This feature requires all users participating in the group feature to complete a form on their individual account.</li>
                      <li>One person in the group must create a chat room and specify how many people in the group are going to vote.
                          An infinite amount of people can join a chat room but the amount of people who are voting must be specified.</li>
                      <li>When a room is created, the other group members must join the chat room by entering the room number into the form field.</li>
                      <li>Once all voters have entered the room, a list of all movies in the cinema will appear.</li>
                      <li>Then please select the movies that you would like to watch. Note, each member of the group must select one movie.</li>
                      <li>In the table provided, each user should assign a preference score from 1 to 10 across all movies. 10 being the
                          most preferred movie and 1 being the least preferred movie. Then confirm your inputs by clicking "submit".</li>
                      <li>Once everyone has left a chat room, it will automatically be deleted.</li>
                      <li>Note, the recommendation cannot be obtained until the last person in the group submits their preference. The last person who
                          submits  will see a  "Get Recommendation" button. Once pressed all users will see the recommendation.</li>
                </ol>
              </div>
        </div>
    </div>
</div>
{% endblock content %}

loop/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1.0"/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous"></head>
    <script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
    <link href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Loop - {{ title }}</title>
    {% else %}
        <title>Loop</title>
    {% endif %}
</head>
<body data-spy="scroll" data-target=".scrollmenu">
<div class="majorContent">
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark nb-colour fixed-top">
        <div class="container">
            {% if current_user.is_authenticated %}
            <a class="navbar-brand mb-0 h1" href="{{ url_for('main.watch') }}">
            <img src="{{ url_for('static', filename = 'images/logo.jpg') }}" alt="logo" width="80" height="40"></a>
            {% else %}
            <a class="navbar-brand mb-0 h1" href="{{ url_for('users.login') }}">
            <img src="{{ url_for('static', filename = 'images/logo.jpg') }}" alt="logo" width="80" height="40"></a>
              {% endif %}
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
                {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('main.profile') }}">Profile</a>
                <a class="nav-item nav-link" href="{{ url_for('main.watch') }}">Watch</a>
                <a class="nav-item nav-link" href="{{ url_for('main.group_landing') }}">Group Recommendation</a>
                <a class="nav-item nav-link" href="{{ url_for('main.contact') }}">Contact</a>
                {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <li class="dropdown">
                  <a class="nav-item nav-link dropdown-toggle" data-toggle="dropdown">{{ current_user.first_name }} {{ current_user.last_name }}</a>
                  <ul class="nav_dropdown dropdown-menu">
                    <li><a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a></li>
                  </ul>
                </li>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('main.contact') }}">Contact</a>
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }} col-md-8">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
      </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</div>
</body>
</html>

loop/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="col-md-8">
    <div class="log_reg_form">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="white_text">
            Create An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
</div>
{% endblock content %}